module.exports = {
  "ALIVE_IMG": "",
  "FOOT": "©ආදරෙ 2G වෙද්දි KG මට 4G උනා නංගි🙂💞",
  "PREFIX": ".",
  "AUTO_READ_STATUS": "true",
  "MODE": "private",
  "BOT_NUMBER": "94712557438",
  "OMDB_API_KEY": "76cb7f39",
  "READ_CMD": "false",
  "AUTO_VOICE": "false",
  "ANTI_BAD": "warn",
  "ANTI_BOT": "false",
  "ANTI_CALL": "true",
  "ANTI_LINK": "false",
  "ANTI_PHOTO": "warn",
  "ANTI_STICKER": "warn",
  "ANTI_DELETE": true,
  "DELETEMSGSENDTO": "94742274855",
  "ALWAYS_ONLINE": "false",
  "MOROCCO_BLOCK": "false",
  "OWNER_NAME": "©𝐌𝐑 shanuwa 𝐎𝐅𝐂 💚",
  "OWNER_NUMBER": "94712557438",
  "AUTO_BIO": "true",
  "AUTO_TYPING": "false",
  "AUTO_RECORDING": "false",
  "WARN_COUNT": "3",
};
